dataset_conf:
  dataset:
    min_duration: 0.4
    max_duration: 30
    sample_rate: 32000
    use_dB_normalization: false
    target_dB: -20
  dataLoader:
    batch_size: 64
    drop_last: true
    num_workers: 8
  eval_conf:
    batch_size: 64
    max_duration: 30
  train_list: '/root/autodl-tmp/deepship_demonet_30s_overlap15s/train.txt'
  test_list: '/root/autodl-tmp/deepship_demonet_30s_overlap15s/test.txt'
  label_list_path: '/root/autodl-tmp/deepship_demonet_30s_overlap15s/label.txt'

preprocess_conf:
  use_hf_model: false
  feature_method: 'MelSpectrogram'
  method_args:
    sample_rate: 32000
    frame_length: 50.0
    frame_shift: 25.0
    n_fft: 4096
    n_mels: 300
    f_min: 100.0
    f_max: 8000.0
    window_type: 'hanning'
    power: 1.0
    center: false
    log_type: 'log'
    transpose: true
    subtract_time_mean: false

model_conf:
  model: 'ResNetAPClassifier'
  model_args:
    num_class: null
    base_channels: 64
    embd_dim: 512
    classifier_hidden_dim: null
    classifier_use_bn: false
    dropout: 0.0
    attention_heads: 8
    attention_dropout: 0.1
    attention_pool_type: 'learnable_query'
    pooling_mode: 'paper_mha'
    paper_mha_readout: 'avg'

optimizer_conf:
  optimizer: 'AdamW'
  optimizer_args:
    lr: !!float 5e-4
    weight_decay: !!float 1e-5
  scheduler: {}

train_conf:
  enable_amp: true
  use_compile: false
  label_smoothing: 0.0
  max_epoch: 100
  log_interval: 10